[tool.poetry]
name = "python-project"
version = "0.1.0"
description = ""
authors = ["Tack Balthazar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Pillow = "^9.0"          
numpy = "^1.21"          
matplotlib = "^3.5"     

# Development dependencies
[tool.poetry.dev-dependencies]
pytest = "^7.0"      
pylint = "^2.14"      
black = "^22.3"      
pandas = "^1.3" 
coverage = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
